// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoftataInfo2DB;

#nullable disable

namespace SoftataInfo2DB.Migrations
{
    [DbContext(typeof(Program.DictionaryContext))]
    [Migration("20250304020446_MyFirstMigration")]
    partial class MyFirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("SoftataInfo2DB.Program+DType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SoftataId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("dTypes");
                });

            modelBuilder.Entity("SoftataInfo2DB.Program+Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DtypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SoftataId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DtypeId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("SoftataInfo2DB.Program+DictionaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DictionaryEntries");
                });

            modelBuilder.Entity("SoftataInfo2DB.Program+GenericCommand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DtypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SoftataId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DtypeId");

                    b.ToTable("GenericCommands");
                });

            modelBuilder.Entity("SoftataInfo2DB.Program+Device", b =>
                {
                    b.HasOne("SoftataInfo2DB.Program+DType", "DType")
                        .WithMany("Devices")
                        .HasForeignKey("DtypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DType");
                });

            modelBuilder.Entity("SoftataInfo2DB.Program+GenericCommand", b =>
                {
                    b.HasOne("SoftataInfo2DB.Program+DType", "DType")
                        .WithMany("Commands")
                        .HasForeignKey("DtypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DType");
                });

            modelBuilder.Entity("SoftataInfo2DB.Program+DType", b =>
                {
                    b.Navigation("Commands");

                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
