// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoftataWebAPI.Data.Db;

#nullable disable

namespace SoftataWebAPI.Migrations
{
    [DbContext(typeof(SoftataDbContext))]
    partial class SoftataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("SoftataWebAPI.Data.Db.DType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SoftataId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("dTypes");
                });

            modelBuilder.Entity("SoftataWebAPI.Data.Db.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DtypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SoftataId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DtypeId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("SoftataWebAPI.Data.Db.GenericCommand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DtypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SoftataId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DtypeId");

                    b.ToTable("GenericCommands");
                });

            modelBuilder.Entity("SoftataWebAPI.Data.Db.Device", b =>
                {
                    b.HasOne("SoftataWebAPI.Data.Db.DType", "DType")
                        .WithMany("Devices")
                        .HasForeignKey("DtypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DType");
                });

            modelBuilder.Entity("SoftataWebAPI.Data.Db.GenericCommand", b =>
                {
                    b.HasOne("SoftataWebAPI.Data.Db.DType", "DType")
                        .WithMany("Commands")
                        .HasForeignKey("DtypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DType");
                });

            modelBuilder.Entity("SoftataWebAPI.Data.Db.DType", b =>
                {
                    b.Navigation("Commands");

                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
